version: '2'
services:
    lbstest-app:
        image: lbstest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lbstest-postgresql:5432/LBStest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=lbstest-elasticsearch:9300
        ports:
            - 8080:8080
    lbstest-postgresql:
        extends:
            file: postgresql.yml
            service: lbstest-postgresql
    lbstest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: lbstest-elasticsearch
